import 'bootstrap/dist/css/bootstrap.min.css'; /** importamos libreria bootstrap */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionAuthProvider from '@/context/SessionAuthProvider';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='container'>
       <SessionAuthProvider>
        <Navbar />
        {children}
        </SessionAuthProvider> 
        </main>
        <footer className='footercenter'><div className="loader"></div>Sitio creado por Vicky Lorena Jorge<div className="loader"></div></footer>
        </body>
    </html>
  );
}
